### ISSUE TITLE
Socket error on client <unknown>, disconnecting.

### ISSUE THREAD

**Issue by coolcodecding** [hometinker12/ESP8266MQTTSSL#2]
I have setup mosquitto on docker using certificates to secure the connection. I have no username and password configured in mosquitto.
I am using your code with CA.crt  to connect my wemos d1 mini to mosquitto.

After inserting my credentials, mqtt data and ca.crt i get the following serial output:

```
Connecting to WiFi.
.......Connected to the WiFi network
Waiting for NTP time sync: .
Current time: Wed Mar 11 19:11:49 2020
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
```

mosquitto gives the following log:

```
1583943307: mosquitto version 1.6.9 starting
1583943307: Config loaded from /mosquitto/config/mosquitto.conf.
1583943307: Opening ipv4 listen socket on port 8883.
1583943307: Opening ipv6 listen socket on port 8883.
1583943312: New connection from 192.168.0.1 on port 8883.
1583943318: Socket error on client <unknown>, disconnecting.
1583943318: New connection from 192.168.0.1 on port 8883.
1583943324: Socket error on client <unknown>, disconnecting.
1583943324: New connection from 192.168.0.1 on port 8883.
```

I used the MQTTfx to connect to mosquitto with the ca.crt file before and it worked fine. Using the console to publish and subscribe also works well.

my mosquitto.conf:

allow_anonymous true

port 8883

cafile /ca.crt
keyfile /server.key
certfile /server.crt
tls_version tlsv1.2

persistence true
persistence_location /mosquitto/data/

Do you have any ideas what could cause the problem?
I have been working on this for literally 50+ hrs ...

**Comment by hometinker12** [comment]
Can you share your code? I have seen a similar issue when using a long lastwill message.
